/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2021-01-30 06:17:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import control.Aluno;
import control.Carrinho;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Wissen | Checkout</title>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Big+Shoulders+Inline+Display:wght@600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/checkout.css\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/b1b1442df1.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("    \r\n");
      out.write("    ");
 Aluno a = (Aluno) session.getAttribute("objUser"); Carrinho c = a.getCarrinho();
    
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <header class=\"header-wissen\">\r\n");
      out.write("    <form class=\"header-wissen\" method=\"post\">\r\n");
      out.write("        <nav class=\"menu-topo-wissen row\">\r\n");
      out.write("        <div class=\"wis-menu col-sm-2\">\r\n");
      out.write("            <a class=\"logo-wissen-a\" href=\"jspHome.jsp\" title=\"Wissen - A Plataforma do Conhecimento\">\r\n");
      out.write("                <img class=\"logo-wissen\" src=\"images/labelwissen.png\" alt=\"WISSEN\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\r\n");
      out.write("        <nav class=\"menu-itens col-sm-6\">\r\n");
      out.write("        \t\r\n");
      out.write("            <span class=\"span-search\">\r\n");
      out.write("                <input type=\"text\" placeholder=\"Pesquisar por um curso\" name=\"search\">\r\n");
      out.write("                <button type=\"submit\" formaction=\"SvSearch\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("            </span>\r\n");
      out.write("            \r\n");
      out.write("        </nav>\r\n");
      out.write("\t\r\n");
      out.write("        <div class=\"login-box col-sm-4 pr-5\">\r\n");
      out.write("        ");
 if(c.getListaCursosCarrinho() != null) { 
      out.write("\r\n");
      out.write("        <a class=\"btn-cart\" href=\"SvCheckout\" role=\"button\" ><i class=\"fas fa-shopping-cart\"></i></a><span class=\"cart-number\">");
      out.print(a.getCarrinho().getListaCursosCarrinho().size() );
      out.write("</span>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <a class=\"btn-cart\" href=\"SvCheckout\" role=\"button\" ><i class=\"fas fa-shopping-cart\"></i></a><span class=\"cart-number\"></span>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <a class=\"btn-heart\" href=\"SvLogout\" role=\"button\" ><i class=\"fas fa-sign-out-alt\"></i></a>\r\n");
      out.write("            <a class=\"btn-cursos\" href=\"meuscursos.jsp\" role=\"button\" >Meus Cursos</a>\r\n");
      out.write("            <a href=\"profile.jsp\"><i class=\"fas fa-user link-login-wissen login-svg\" ></i></a>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Mobile -->\r\n");
      out.write("    <nav class=\"nav-mobile\">\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <span class=\"span-search\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"Pesquisar por um curso\">\r\n");
      out.write("            <button type=\"submit\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("        </span>\r\n");
      out.write("            \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div class=\"burger\">\r\n");
      out.write("            <div class=\"line1\"></div>\r\n");
      out.write("            <div class=\"line2\"></div>\r\n");
      out.write("            <div class=\"line3\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"nav-links\">\r\n");
      out.write("            <li class=\"nav-li1\">");
 if(c.getListaCursosCarrinho() != null) { 
      out.write("\r\n");
      out.write("        <a class=\"btn-cart\" href=\"SvCheckout\" role=\"button\" ><i class=\"fas fa-shopping-cart\"></i></a><span class=\"cart-number\">");
      out.print(a.getCarrinho().getListaCursosCarrinho().size() );
      out.write("</span>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <a class=\"btn-cart\" href=\"SvCheckout\" role=\"button\" ><i class=\"fas fa-shopping-cart\"></i></a><span class=\"cart-number\"></span>\r\n");
      out.write("            ");
 } 
      out.write("</li>\r\n");
      out.write("            <li><a href=\"profile.jsp\"><i class=\"fas fa-user link-login-wissen login-svg\"></i></a></li>\r\n");
      out.write("            <li ><a class=\"btn-cursos\" href=\"meuscursos.jsp\" role=\"button\" >Meus Cursos</a></li>\r\n");
      out.write("            <li ><a class=\"btn-heart\" href=\"SvLogout\" role=\"button\" ><i class=\"fas fa-sign-out-alt\"></i></a></li>\r\n");
      out.write("            \r\n");
      out.write("            <li><a class=\"logo-wissen-a\" href=\"jspHome.jsp\" title=\"Wissen - A Plataforma do Conhecimento\">\r\n");
      out.write("                <img class=\"logo-wissen\" src=\"images/labelwissen.png\" alt=\"WISSEN\">\r\n");
      out.write("            </a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    </form>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"container-fluid\">\r\n");
      out.write("        <form action=\"SvCadastroPedido\" method=\"POST\">\r\n");
      out.write("            <input type=\"hidden\" name=\"id_cursos\" id=\"id_cursos\" value=\"\">\r\n");
      out.write("            <input type=\"hidden\" name=\"total-price\" id=\"total-price\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("        <section class=\"row main-section\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-8 left-col\">\r\n");
      out.write("            <p class=\"p-title\">Carrinho</p>\r\n");
      out.write("            <div class=\"divider\">\r\n");
      out.write("                <div class=\"div-products\">\r\n");
      out.write("                    <div class=\"row labels\">\r\n");
      out.write("                        <p class=\"col-md-8\">Produtos</p>\r\n");
      out.write("                        <p class=\"col-md-4\">Valor Total</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 double price = 0;
                    for(int i = 0; i < a.getCarrinho().getListaCursosCarrinho().size(); i++) { 
      out.write("\r\n");
      out.write("                    <div class=\"courses row align-items-center\">\r\n");
      out.write("                        <div class=\"col-md-8 item\">\r\n");
      out.write("                            <img src=\"images/");
      out.print( a.getCarrinho().getListaCursosCarrinho().get(i).getPhoto());
      out.write("\" alt=\"\">\r\n");
      out.write("                            <div class=\"p-text\">");
      out.print( a.getCarrinho().getListaCursosCarrinho().get(i).getTitle() );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                            <div class=\"p-text\">R$ <span class=\"course-price\">");
      out.print( a.getCarrinho().getListaCursosCarrinho().get(i).getPrice() );
      out.write("</span> </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-1\"><button class=\"btn-x\" type=\"button\">X</button></div>\r\n");
      out.write("                        <input type=\"hidden\" class=\"id-curso\" value=\"");
      out.print(a.getCarrinho().getListaCursosCarrinho().get(i).getId());
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
price += a.getCarrinho().getListaCursosCarrinho().get(i).getPrice(); 
      out.write("\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <div class=\"total\">\r\n");
      out.write("                        <p class=\"total-price\">Total: R$ <span id=\"preco-total\">");
      out.print( price );
      out.write("</span></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-4 right-col\">\r\n");
      out.write("            <p class=\"p-title\">Pagamento</p>\r\n");
      out.write("            <div class=\"div-checkout\">\r\n");
      out.write("                <label class=\"l-text\">Método de Pagamento</label>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <label class=\"form-check-label\">\r\n");
      out.write("                    <input type=\"radio\" class=\"form-check-input\" name=\"payment-method\" id=\"paypal\" value=\"PayPal\" checked>\r\n");
      out.write("                    <i class=\"fab fa-cc-paypal\"></i> PayPal\r\n");
      out.write("                  </label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <label class=\"form-check-label\">\r\n");
      out.write("                    <input type=\"radio\" class=\"form-check-input\" name=\"payment-method\" id=\"credit-card\" value=\"Cartão de Crédito\">\r\n");
      out.write("                    <i class=\"fas fa-credit-card\"></i> Cartão de Crédito\r\n");
      out.write("                  </label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <label class=\"form-check-label\">\r\n");
      out.write("                    <input type=\"radio\" class=\"form-check-input\" name=\"payment-method\" id=\"boleto\" value=\"Boleto\">\r\n");
      out.write("                    <i class=\"fas fa-money-bill\"></i> Boleto\r\n");
      out.write("                  </label>\r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group first-input\">\r\n");
      out.write("                    <label class=\"l-text\">Nome no Cartão:</label>\r\n");
      out.write("                    <input type=\"text\"\r\n");
      out.write("                      class=\"form-control card-info\" name=\"name\" aria-describedby=\"helpId\" placeholder=\"Ex: Maria M Silva\" disabled>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"l-text\">Número do Cartão:</label>\r\n");
      out.write("                    <input type=\"text\"\r\n");
      out.write("                      class=\"form-control card-info\" name=\"card-number\" aria-describedby=\"helpId\" placeholder=\"\" disabled>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"form-group col-md-8\">\r\n");
      out.write("                    <label class=\"l-text\">Data de Validade (mm/aa)</label>\r\n");
      out.write("                    <input type=\"text\"\r\n");
      out.write("                        class=\"form-control card-info\" name=\"exp-date\" aria-describedby=\"helpId\" placeholder=\"\" disabled>\r\n");
      out.write("                  </div>  \r\n");
      out.write("                  <div class=\"form-group col-md-4\">\r\n");
      out.write("                    <label class=\"l-text\">CVV</label>\r\n");
      out.write("                    <input type=\"number\"\r\n");
      out.write("                        class=\"form-control card-info\" name=\"cvv\" aria-describedby=\"helpId\" placeholder=\"\" disabled>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <input name=\"\" id=\"\" class=\"btn btn-primary btn-finalizar\" type=\"submit\" value=\"Finalizar Compra\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("    </form>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("    <!-- Optional JavaScript -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.1.1.min.js\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"js/nav.js\"></script>\r\n");
      out.write("    <script src=\"js/checkout.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
