/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2021-01-30 06:34:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import control.Curso;
import control.Modulo;
import java.util.List;

public final class editarcurso_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Wissen | Curso</title>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Big+Shoulders+Inline+Display:wght@600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/b1b1442df1.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/course.css\">\r\n");
      out.write("    \r\n");
      out.write("    ");
Curso c = (Curso) session.getAttribute("objCurso"); 
    
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <header class=\"header-wissen\">\r\n");
      out.write("        <nav class=\"menu-topo-wissen row\">\r\n");
      out.write("        <div class=\"wis-menu col-sm-2\">\r\n");
      out.write("            <a class=\"logo-wissen-a\" href=\"jspHomeInstrutor.jsp\" title=\"Wissen - A Plataforma do Conhecimento\">\r\n");
      out.write("                <img class=\"logo-wissen\" src=\"images/labelwissen.png\" alt=\"WISSEN\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"menu-itens col-sm-6\">\r\n");
      out.write("            <span class=\"nav-item\"><a href=\"#novo-curso\">Criar Curso</a></span>\r\n");
      out.write("            <span class=\"nav-item\"><a href=\"#gerenciar-curso\">Gerenciar Cursos</a></span>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"login-box col-sm-4 pr-5\">\r\n");
      out.write("            <a class=\"btn-heart\" href=\"SvLogout\" role=\"button\" ><i class=\"fas fa-sign-out-alt\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fas fa-user link-login-wissen login-svg\" ></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Mobile -->\r\n");
      out.write("    <nav class=\"nav-mobile\">\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <span class=\"wis-menu\">\r\n");
      out.write("            <a class=\"logo-wissen-a\" href=\"home.html\" title=\"Wissen - A Plataforma do Conhecimento\">\r\n");
      out.write("                <img class=\"logo-wissen\" src=\"images/labelwissen.png\" alt=\"WISSEN\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </span>\r\n");
      out.write("            \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div class=\"burger\">\r\n");
      out.write("            <div class=\"line1\"></div>\r\n");
      out.write("            <div class=\"line2\"></div>\r\n");
      out.write("            <div class=\"line3\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"nav-links\">\r\n");
      out.write("            <li class=\"nav-li1\"><a href=\"#novo-curso\">Criar Curso</a></li>\r\n");
      out.write("            <li ><a href=\"#gerenciar-curso\">Gerenciar Cursos</a></li>\r\n");
      out.write("            <li ><a class=\"btn-heart\" href=\"SvLogout\" role=\"button\" ><i class=\"fas fa-sign-out-alt\"></i> Logout</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fas fa-user link-login-wissen login-svg\"></i> Perfil</a></li>\r\n");
      out.write("            <li><a class=\"logo-wissen-a\" href=\"home.html\" title=\"Wissen - A Plataforma do Conhecimento\">\r\n");
      out.write("                <img class=\"logo-wissen\" src=\"images/labelwissen.png\" alt=\"WISSEN\">\r\n");
      out.write("            </a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"container-fluid\">\r\n");
      out.write("        <div class=\"main-div row\">\r\n");
      out.write("            <div class=\"left-space col-md-6\">\r\n");
      out.write("                <div class=\"card\" style=\"width: 16rem; height: 370px;\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"images/");
      out.print( c.getPhoto() );
      out.write("\" alt=\"Imagem de capa do card\" style=\"height: 150px;\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <h5 class=\"card-title\" style=\"font-size: 16px;\">");
      out.print( c.getTitle() );
      out.write("</h5>\r\n");
      out.write("                      <p class=\"card-text\" style=\"font-size: 12px;\">Por: ");
      out.print( c.getNameInstrutor() );
      out.write("</p>\r\n");
      out.write("                    <div class=\"rating\">\r\n");
      out.write("                      <span class=\"star-text\"></span>\r\n");
      out.write("                      <span class=\"fa fa-star checked\"></span>\r\n");
      out.write("                      <span class=\"fa fa-star checked\"></span>\r\n");
      out.write("                      <span class=\"fa fa-star checked\"></span>\r\n");
      out.write("                      <span class=\"fa fa-star checked\"></span>\r\n");
      out.write("                      <span class=\"fa fa-star\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                      <p class=\"price\">R$");
      out.print(c.getPrice() );
      out.write("</p>\r\n");
      out.write("                      <a href=\"#\" class=\"buy-btn\">Ver Curso</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"right-space col-md-6\">\r\n");
      out.write("                <form method=\"POST\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"id_curso\" value=\"");
      out.print(c.getId());
      out.write("\">\r\n");
      out.write("                    <div class=\"btns\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-outline-primary\" onclick=\"modulo()\">Criar Módulo</button>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-outline-secondary btn-form\" onclick=\"aula()\">Adiconar Aula</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 String msg = (String) request.getAttribute("msg");
                    if(msg != null && !msg.isEmpty()){ 
      out.write("\r\n");
      out.write("                    \t<div class=\"alert alert-success mt-4\" role=\"alert\">\r\n");
      out.write("  \t\t\t\t\t\t\t");
      out.print( msg );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                    ");
}
                    
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 String errorMsg = (String) request.getAttribute("errorMsg");
                    if(errorMsg != null && !errorMsg.isEmpty()){ 
      out.write("\r\n");
      out.write("                    \t<div class=\"alert alert-danger mt-4\" role=\"alert\">\r\n");
      out.write("  \t\t\t\t\t\t\t");
      out.print( errorMsg );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                    ");
}
                    
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-modulo\">\r\n");
      out.write("                        <h3>Criar Módulo</h3>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label for=\"\">Título do Módulo</label>\r\n");
      out.write("                          <input type=\"text\" name=\"nome-modulo\" class=\"form-control\" placeholder=\"\" aria-describedby=\"helpId\">\r\n");
      out.write("                          <small id=\"helpId\" class=\"text-muted\">O Título deve ser objetivo</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <button formaction=\"SvCriarModulo\" type=\"submit\" class=\"btn btn-primary\">Adicionar Módulo</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-aula\">\r\n");
      out.write("                        <h3>Adiconar Aula</h3>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                        ");
Modulo m = new Modulo();
                   		List<Modulo> list = m.searchModulos(c);
                        if(list != null) { 
      out.write("\r\n");
      out.write("                          <label for=\"\">Módulo da Aula</label>\r\n");
      out.write("                          <select class=\"form-control\" name=\"modulo-aula\">\r\n");
      out.write("                          ");
 
                          for(int i = 0; i < list.size(); i++) { 
                          
                          
      out.write("\r\n");
      out.write("                            <option value=\"");
      out.print(list.get(i).getId());
      out.write("\">Módulo ");
      out.print( i + 1 );
      out.write(':');
      out.write(' ');
      out.print( list.get(i).getTitle() );
      out.write("</option>\r\n");
      out.write("                            ");
  } 
      out.write("\r\n");
      out.write("                          </select>\r\n");
      out.write("                        ");
 } else {
      out.write("\r\n");
      out.write("                        <div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("  \t\t\t\t\t\t\tAinda não existem módulos cadastrados no curso!\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"\">Título da Aula</label>\r\n");
      out.write("                            <input type=\"text\" name=\"nome-aula\" class=\"form-control\" placeholder=\"\" aria-describedby=\"helpId\">\r\n");
      out.write("                          </div>\r\n");
      out.write("\r\n");
      out.write("                          <div class=\"form-group\">\r\n");
      out.write("                          <label for=\"Vídeo Aula\">Vídeo Aula</label>\r\n");
      out.write("                          <div class=\"custom-file\">\r\n");
      out.write("                            <input type=\"file\" class=\"custom-file-input\" name=\"video-aula\">\r\n");
      out.write("                            <label class=\"custom-file-label\" for=\"customFile\">Escolher Arquivo</label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                          <label for=\"Vídeo Aula\">Material Opcional</label>\r\n");
      out.write("                          <div class=\"custom-file\">\r\n");
      out.write("                            <input type=\"file\" class=\"custom-file-input\" name=\"material-aula\">\r\n");
      out.write("                            <label class=\"custom-file-label\" for=\"customFile\">Escolher Arquivo</label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("  \r\n");
      out.write("                          <button formaction=\"SvAddAula\" type=\"submit\" class=\"btn btn-primary\">Adicionar Aula</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("      \r\n");
      out.write("    <!-- Optional JavaScript -->\r\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- JavaScript -->\r\n");
      out.write("    <script src=\"js/nav.js\"></script>\r\n");
      out.write("    <script src=\"js/course.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
