/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2021-01-30 06:09:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import control.Curso;
import control.Instrutor;
import java.util.List;

public final class jspHomeInstrutor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Wissen | Home Instrutor</title>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Big+Shoulders+Inline+Display:wght@600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/home.css\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/b1b1442df1.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("    \r\n");
      out.write("    ");
 Instrutor instrutor = (Instrutor) session.getAttribute("objUser");
    
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <header class=\"header-wissen\">\r\n");
      out.write("        <nav class=\"menu-topo-wissen row\">\r\n");
      out.write("        <div class=\"wis-menu col-sm-2\">\r\n");
      out.write("            <a class=\"logo-wissen-a\" href=\"jspHomeInstrutor.jsp\" title=\"Wissen - A Plataforma do Conhecimento\">\r\n");
      out.write("                <img class=\"logo-wissen\" src=\"images/labelwissen.png\" alt=\"WISSEN\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"menu-itens col-sm-6\">\r\n");
      out.write("            <span class=\"nav-item\"><a href=\"#novo-curso\">Criar Curso</a></span>\r\n");
      out.write("            <span class=\"nav-item\"><a href=\"#gerenciar-curso\">Gerenciar Cursos</a></span>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"login-box col-sm-4 pr-5\">\r\n");
      out.write("            <a class=\"btn-heart\" href=\"SvLogout\" role=\"button\" ><i class=\"fas fa-sign-out-alt\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fas fa-user link-login-wissen login-svg\" ></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Mobile -->\r\n");
      out.write("    <nav class=\"nav-mobile\">\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <span class=\"wis-menu\">\r\n");
      out.write("            <a class=\"logo-wissen-a\" href=\"home.html\" title=\"Wissen - A Plataforma do Conhecimento\">\r\n");
      out.write("                <img class=\"logo-wissen\" src=\"images/labelwissen.png\" alt=\"WISSEN\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </span>\r\n");
      out.write("            \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div class=\"burger\">\r\n");
      out.write("            <div class=\"line1\"></div>\r\n");
      out.write("            <div class=\"line2\"></div>\r\n");
      out.write("            <div class=\"line3\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"nav-links\">\r\n");
      out.write("            <li class=\"nav-li1\"><a href=\"#novo-curso\">Criar Curso</a></li>\r\n");
      out.write("            <li ><a href=\"#gerenciar-curso\">Gerenciar Cursos</a></li>\r\n");
      out.write("            <li ><a class=\"btn-heart\" href=\"SvLogout\" role=\"button\" ><i class=\"fas fa-sign-out-alt\"></i> Logout</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fas fa-user link-login-wissen login-svg\"></i> Perfil</a></li>\r\n");
      out.write("            <li><a class=\"logo-wissen-a\" href=\"home.html\" title=\"Wissen - A Plataforma do Conhecimento\">\r\n");
      out.write("                <img class=\"logo-wissen\" src=\"images/labelwissen.png\" alt=\"WISSEN\">\r\n");
      out.write("            </a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main-col\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row-image\">\r\n");
      out.write("                <img src=\"images/logowissen.png\" alt=\"Wissen\">\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 String msg = (String) request.getAttribute("msg");
                    if(msg != null && !msg.isEmpty()){ 
      out.write("\r\n");
      out.write("                    \t<div class=\"alert alert-success mt-4\" role=\"alert\">\r\n");
      out.write("  \t\t\t\t\t\t\t");
      out.print( msg );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                    ");
}
                    
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 String errorMsg = (String) request.getAttribute("errorMsg");
                    if(errorMsg != null && !errorMsg.isEmpty()){ 
      out.write("\r\n");
      out.write("                    \t<div class=\"alert alert-danger mt-4\" role=\"alert\">\r\n");
      out.write("  \t\t\t\t\t\t\t");
      out.print( errorMsg );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                    ");
}
                    
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row-banner\" style=\"margin-top: 5%;\" id=\"novo-curso\">\r\n");
      out.write("                <p class=\"banner-p\">Criar Novo Curso</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!--Linha de Criar Cursos -->\r\n");
      out.write("            <div class=\"row-create row-one\">\r\n");
      out.write("                <form action=\"SvCadastroCurso\" method=\"POST\" class=\"form-curso\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <label for=\"\">Nome do Curso</label>\r\n");
      out.write("                      <input type=\"text\" name=\"nome-curso\" id=\"\" class=\"form-control\" placeholder=\"\" aria-describedby=\"helpId\">\r\n");
      out.write("                      <small id=\"helpId\" class=\"text-muted\">Tenha certeza de que o título seja chamativo. (25-50 caracteres)</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                          <label for=\"\">Nome Aparente do Instrutor</label>\r\n");
      out.write("                          <input type=\"text\" name=\"instrutor-curso\" id=\"\" class=\"form-control\" placeholder=\"\" aria-describedby=\"helpId\">\r\n");
      out.write("                          <small id=\"helpId\" class=\"text-muted\">Nome do instrutor que será visível no curso (Ex: Bruno Correa)</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                          <label for=\"\">Preço (Em Reais)</label>\r\n");
      out.write("                          <input type=\"number\" name=\"preco-curso\" id=\"\" class=\"form-control\" placeholder=\"\" aria-describedby=\"helpId\">\r\n");
      out.write("                          <small id=\"helpId\" class=\"text-muted\">Obs: Divisão - 70% do Instrutor e 30% da Plataforma | Para curso gratuito colocar 0.00</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                          <label for=\"\">Descrição do Curso</label>\r\n");
      out.write("                          <textarea class=\"form-control\" name=\"descricao-curso\" id=\"\" rows=\"3\"></textarea>\r\n");
      out.write("                          <small id=\"helpId\" class=\"text-muted\">Breve descrição que irá aparecer como subtítulo na página do curso</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                          <label for=\"\">Requisitos</label>\r\n");
      out.write("                          <textarea class=\"form-control\" name=\"requisitos-curso\" id=\"\" rows=\"3\"></textarea>\r\n");
      out.write("                          <small id=\"helpId\" class=\"text-muted\">Requisitos ou conhecimentos prévios necessários para fazer o curso </small>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                            <label for=\"\">Idioma do Curso</label>\r\n");
      out.write("                            <input type=\"text\" name=\"idioma-curso\" id=\"\" class=\"form-control\" placeholder=\"\" aria-describedby=\"helpId\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                            <label for=\"\">Para Quem é Este Curso</label>\r\n");
      out.write("                            <textarea class=\"form-control\" name=\"publico-curso\" id=\"\" rows=\"1\"></textarea>\r\n");
      out.write("                            <small id=\"helpId\" class=\"text-muted\">Público para o qual seu curso é destinado </small>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                            <label>Foto de Capa</label>\r\n");
      out.write("                          <div class=\"custom-file\">\r\n");
      out.write("                              <input type=\"file\" class=\"custom-file-input foto-capa\" name=\"foto-curso\" id=\"customFile\">\r\n");
      out.write("                              <label class=\"custom-file-label\">Escolher Arquivo</label>\r\n");
      out.write("                              <small id=\"helpId\" class=\"text-muted\">Escolha uma foto que atraia público para o curso</small>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                          <label for=\"\">Gênero</label>\r\n");
      out.write("                          <select class=\"form-control\" name=\"genero-curso\" id=\"\">\r\n");
      out.write("                            <option>Programação</option>\r\n");
      out.write("                            <option>Tecnologia</option>\r\n");
      out.write("                            <option>Marketing</option>\r\n");
      out.write("                            <option>Música</option>\r\n");
      out.write("                            <option>Esporte</option>\r\n");
      out.write("                            <option>Jogos</option>\r\n");
      out.write("                            <option>Economia</option>\r\n");
      out.write("                            <option>Design</option>\r\n");
      out.write("                          </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("                        <div class=\"form-group col-md-12\">\r\n");
      out.write("                          <button type=\"submit\" class=\"create-btn\"  >Criar Curso</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("    \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Banner Entre Rows de Cursos -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row-banner\" id=\"gerenciar-curso\">\r\n");
      out.write("                <p class=\"banner-p\">Gerenciar Cursos</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Linha de Meus Cursos -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row-courses\">\r\n");
      out.write("                <h2 class=\"font-weight-light\" style=\"font-size: 25px; margin-left: 5%;\">Meus Cursos</h2>\r\n");
      out.write("                <hr>\r\n");
      out.write("                \r\n");
      out.write("                <form method = \"post\" action= \"SvAbrirEditar\" id=\"form-cursos\">\r\n");
      out.write("                <input type=\"hidden\" name=\"id-curso\" id=\"id-curso\" value=\"\">\r\n");
      out.write("                \r\n");
      out.write("    <div class=\"row mx-auto my-auto justify-content-center\">\r\n");
      out.write("        <div id=\"recipeCarousel\" class=\"carousel slide w-100\" data-ride=\"carousel\">\r\n");
      out.write("            <div class=\"carousel-inner w-100\" role=\"listbox\" style=\"margin-left: 5%;\">\r\n");
      out.write("            ");
 List<Curso> listaCursos = instrutor.getListaCursos();
            if(listaCursos != null){
            	for(int i = 0; i < listaCursos.size(); i++) { 
            		if(i == 0) { 
      out.write("\r\n");
      out.write("            \t\t<div class=\"carousel-item active\">\r\n");
      out.write("            \t");
} else { 
      out.write("\r\n");
      out.write("            \t<div class=\"carousel-item\">\r\n");
      out.write("            \t");
 } 
      out.write("\r\n");
      out.write("                    <div class=\"col-sm-4\">\r\n");
      out.write("                        <div class=\"card\" style=\"width: 16rem; height: 370px;\">\r\n");
      out.write("                            <img class=\"card-img-top\" src=\"images/");
      out.print( listaCursos.get(i).getPhoto() );
      out.write("\" alt=\"Imagem de capa do card\" style=\"height: 150px;\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                              <h5 class=\"card-title\" style=\"font-size: 16px;\">");
      out.print( listaCursos.get(i).getTitle() );
      out.write("</h5>\r\n");
      out.write("                              <p class=\"card-text\" style=\"font-size: 12px;\">Por: ");
      out.print( listaCursos.get(i).getNameInstrutor() );
      out.write("</p>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                              <span class=\"star-text\">4.0</span>\r\n");
      out.write("                              <span class=\"fa fa-star checked\"></span>\r\n");
      out.write("                              <span class=\"fa fa-star checked\"></span>\r\n");
      out.write("                              <span class=\"fa fa-star checked\"></span>\r\n");
      out.write("                              <span class=\"fa fa-star checked\"></span>\r\n");
      out.write("                              <span class=\"fa fa-star\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                              <p class=\"price\">R$");
      out.print( listaCursos.get(i).getPrice() );
      out.write("</p>\r\n");
      out.write("                              <a href=\"#\" class=\"buy-btn\">Editar</a>\r\n");
      out.write("                              <input type=\"hidden\" class=\"id_curso\" value=\"");
      out.print( listaCursos.get(i).getId());
      out.write("\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            \t");
 
            	} 
            } else { 
      out.write("\r\n");
      out.write("            \t<div class=\"carousel-item active\">\r\n");
      out.write("                    <div class=\"col-sm-4\">\r\n");
      out.write("                        <div class=\"card\" style=\"width: 16rem; height: 370px;\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                              <h5 class=\"card-title\" style=\"font-size: 16px;\">Você ainda não tem Cursos</h5>\r\n");
      out.write("                              <p class=\"card-text\" style=\"font-size: 12px;\">Crie um curso e volte aqui para editá-lo!</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("           ");
 }
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <a class=\"carousel-control-prev w-auto\" href=\"#recipeCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon bg-dark border border-dark rounded-circle\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"sr-only\">Previous</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"carousel-control-next w-auto\" href=\"#recipeCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon bg-dark border border-dark rounded-circle\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"sr-only\">Next</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <footer class=\"footer-wissen p-5\">\r\n");
      out.write("        \r\n");
      out.write("                <div class=\"row align-items-center justify-content-center\">\r\n");
      out.write("                    <img class=\"svg-cursos col-sm-2\" src=\"images/wissen full.png\" alt=\"\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"footer-slogan col-sm-4\">\r\n");
      out.write("                        <h1>A Plataforma do<span class=\"txt-destaque2\"> Conhecimento</span></h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("        \r\n");
      out.write("                    <div class=\"col-sm-3 copyright pt-2 \">\r\n");
      out.write("                        <p>&copy; Desenvolvido por Altmann Softwares</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("            </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("    <!-- Optional JavaScript -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"js/nav.js\"></script>\r\n");
      out.write("    <script src=\"js/homeinstrutor.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("    .carousel-inner .carousel-item > div {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("    .carousel-inner .carousel-item > div:first-child {\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-inner .carousel-item.active,\r\n");
      out.write(".carousel-inner .carousel-item-next,\r\n");
      out.write(".carousel-inner .carousel-item-prev {\r\n");
      out.write("    display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* display 3 */\r\n");
      out.write("@media (min-width: 768px) {\r\n");
      out.write("    \r\n");
      out.write("    .carousel-inner .carousel-item-right.active,\r\n");
      out.write("    .carousel-inner .carousel-item-next {\r\n");
      out.write("      transform: translateX(33.333%);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .carousel-inner .carousel-item-left.active, \r\n");
      out.write("    .carousel-inner .carousel-item-prev {\r\n");
      out.write("      transform: translateX(-33.333%);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-inner .carousel-item-right,\r\n");
      out.write(".carousel-inner .carousel-item-left{ \r\n");
      out.write("  transform: translateX(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        $('#recipeCarousel').carousel({\r\n");
      out.write("  interval: 10000\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("$('.carousel .carousel-item').each(function(){\r\n");
      out.write("    var minPerSlide = 3;\r\n");
      out.write("    var next = $(this).next();\r\n");
      out.write("    if (!next.length) {\r\n");
      out.write("    next = $(this).siblings(':first');\r\n");
      out.write("    }\r\n");
      out.write("    next.children(':first-child').clone().appendTo($(this));\r\n");
      out.write("    \r\n");
      out.write("    for (var i=0;i<minPerSlide;i++) {\r\n");
      out.write("        next=next.next();\r\n");
      out.write("        if (!next.length) {\r\n");
      out.write("        \tnext = $(this).siblings(':first');\r\n");
      out.write("      \t}\r\n");
      out.write("        \r\n");
      out.write("        next.children(':first-child').clone().appendTo($(this));\r\n");
      out.write("      }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
